In [2]:
#기본자료형 : 정수 실수 문자열 부울
#파이썬자료형 : 리스트 튜플 딕셔너리 집합
#numpy : 배열자료형 : Numeric Python : 숫자를 다루는 배열 자료형
#      : 리스트랑 비슷함
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy
num = numpy.random.randint(10)
print(num)

2


In [7]:
import numpy as np #numpy를 불러오고 np로 명칭하겠다
num = np.random.randint(10) #np로 사용해야함
print(num)

7


In [10]:
#1차원 배열
num1 = np.random.randint(10, size=6) #크기가 6인 1차원배열
print(num1)

[9 1 4 5 9 5]


In [16]:
l = [9,1,4,5,9,5]
print(l) #[9, 1, 4, 5, 9, 5] 리스트(콤마있음)
#          0  1  2  3  4  5 :index 
print(num1) # [9 1 4 5 9 5] 배열(콤마없음)

#indexing
print(l[1])
print(num1[1])
print(l[4])
print(num1[4])

#slicing
print(l[2:4])
print(num1[2:4])

[9, 1, 4, 5, 9, 5]
[9 1 4 5 9 5]
1
1
9
9
[4, 5]
[4 5]


In [19]:
#2차원배열
num2 = np.random.randint(10, size=(2, 6)) #2행 6열
print(num2)

[[4 3 7 2 4 1]
 [8 3 8 1 8 9]]


In [26]:
l2 = [[4, 3, 7, 2, 4, 1],[8, 3, 8, 1, 8, 9]]
#리스트를 포함하고 있는 리스트와 같다
print(l2)
print(num2)
print(l2[1][2])
print(num2[1][2]) #리스트 표현식
print(num2[1, 2]) #행,열 : 배열표현식

[[4, 3, 7, 2, 4, 1], [8, 3, 8, 1, 8, 9]]
[[4 3 7 2 4 1]
 [8 3 8 1 8 9]]
8
8
8


In [44]:
#[9, 1, 4, 5, 9, 5]
# 0  1  2  3  4  5 : index
#-6 -5 -4 -3 -2 -1
#[9  1  4  5  9  5]
# 0  1  2  3  4  5 : 열
#-6 -5 -4 -3 -2 -1
print(l) #리스트
print(num1) #1차원배열
print(l[1])
print(num1[1])
print(l[-5])
print(num1[-5])
print(l[2:4])
print(num1[2:4])
print(l[-4:-2])
print(num1[-4:-2])
print(l[0:3]) #0생략가능
print(l[:3])
print(num1[:3])
print(l[3:6])
print(l[3:]) #끝번호 생략가능

#전체를 하나씩 건너뛰기
print(l[::2])
print(num1[::2])
print(l[::-1])
print(num1[::-1])
l[1] = 10
print(l)
print(num1)
num1[1] = 10
print(num1)

[9, 10, 4, 5, 9, 5]
[ 9 10  4  5  9  5]
10
10
10
10
[4, 5]
[4 5]
[4, 5]
[4 5]
[9, 10, 4]
[9, 10, 4]
[ 9 10  4]
[5, 9, 5]
[5, 9, 5]
[9, 4, 9]
[9 4 9]
[5, 9, 5, 4, 10, 9]
[ 5  9  5  4 10  9]
[9, 10, 4, 5, 9, 5]
[ 9 10  4  5  9  5]
[ 9 10  4  5  9  5]


In [48]:
#[[4, 3, 7, 2, 4, 1], [8, 3, 8, 1, 8, 9]]
#        0index             1index
#       -2index            -1index
#  0  1  2  3  4  5    0  1  2  3  4  5 
#[[4  3  7  2  4  1]  [8  3  8  1  8  9]]
#         0행                1행
print(l2)
print(num2)
print(l2[0][2])
print(num2[0][2])
print(l2[-2][-4])
print(num2[-2][-4])
print(num2[-2, -4])

[[4, 3, 7, 2, 4, 1], [8, 3, 8, 1, 8, 9]]
[[4 3 7 2 4 1]
 [8 3 8 1 8 9]]
7
7
7
7
7


In [51]:
num3 = np.random.randint(10, size=(3,4)) #3행 4열 (집합)
print(num3)

[[1 4 6 6]
 [0 5 8 4]
 [4 3 1 9]]


In [54]:
l3 = [[1, 4, 6, 6],[0, 5, 8, 4],[4, 3, 1, 9]]
print(l3)

[[1, 4, 6, 6], [0, 5, 8, 4], [4, 3, 1, 9]]


In [72]:
'''
리스트
[[1 4 6 6]        #0index
 [0 5 8 4]        #1index
 [4 3 1 9]]       #2index

배열
 [[1, 4, 6, 6],   #0행
  [0, 5, 8, 4],   #1행
  [4, 3, 1, 9]]   #2행
'''
print(l3[1]) #index
print(num3[1]) #1행
print(l3[:][:2])
print(num3[:][:2])#리스트표현식 : 전체를 가지고 오는 것은 표현가능
print(num3[:, :3])#배열표현식 : 일부만 가지고 오는 표현이 가능
print(l3[:][::2])
print(num3[:][::2])
print(num3[:, ::2]) #[행, 열]
print(l3[::2][::2]) #l3[::2]까지만 표현가능
print(num3[::2][::2])
print(num3[::2, ::2])

print(l3[:][::-1])
print(num3[:][::-1])
print(num3[:, ::-1])
print(num3[::-1, :])
print(num3[::-1, ::-1])

[0, 5, 8, 4]
[0 5 8 4]
[[1, 4, 6, 6], [0, 5, 8, 4]]
[[1 4 6 6]
 [0 5 8 4]]
[[1 4 6]
 [0 5 8]
 [4 3 1]]
[[1, 4, 6, 6], [4, 3, 1, 9]]
[[1 4 6 6]
 [4 3 1 9]]
[[1 6]
 [0 8]
 [4 1]]
[[1, 4, 6, 6]]
[[1 4 6 6]]
[[1 6]
 [4 1]]
[[4, 3, 1, 9], [0, 5, 8, 4], [1, 4, 6, 6]]
[[4 3 1 9]
 [0 5 8 4]
 [1 4 6 6]]
[[6 6 4 1]
 [4 8 5 0]
 [9 1 3 4]]
[[4 3 1 9]
 [0 5 8 4]
 [1 4 6 6]]
[[9 1 3 4]
 [4 8 5 0]
 [6 6 4 1]]


In [79]:
l3[0][1]
print(l3)
print(num3[0][1])
num3[0][1] = 40   #리스트 표현식(배열에서 가능하지만 사용을 자제)
print(num3)
num3[0][1] = 400  #배열 표현식(주로사용)
print(num3)

[[1, 4, 6, 6], [0, 5, 8, 4], [4, 3, 1, 9]]
400
[[ 1 40  6  6]
 [ 0  5  8  4]
 [ 4  3  1  9]]
[[  1 400   6   6]
 [  0   5   8   4]
 [  4   3   1   9]]


In [85]:
###배열을 만드는 방법
# 1. random을 이용하는 방법
num = np.random.randint(10)
print(num)
num = np.random.randint(10, size=6) #1차원 배열
print(num)                          #열의 집합
num = np.random.randint(10, size=(3,4)) #행,열 : 2차원배열
print(num)                              # 1차원 집합체 : 1차원 = 행
num = np.random.randint(10, size=(3,3,4)) #면,행,열 : 3차원배열
print(num)                                #2차원의 집합 : 2차원 = 면

0
[6 9 8 8 3 3]
[[2 6 3 6]
 [4 0 8 2]
 [5 0 4 1]]
[[[9 7 1 6]
  [8 8 0 2]
  [1 6 6 2]]

 [[0 5 3 7]
  [6 7 4 2]
  [6 6 1 8]]

 [[1 6 1 7]
  [8 8 8 8]
  [1 6 1 5]]]


In [86]:
for num in range(10): #range함수는 파이썬
    print(num)

0
1
2
3
4
5
6
7
8
9


In [103]:
# 2. arange()함수를 사용하는 방법 : 1차원
#arange함수는 numpy에 있는 함수
#1차원 배열을 만들어주는 함수
print(np.arange(10)) #[0 1 2 3 4 5 6 7 8 9]
m1 = np.arange(9)#0~8 1차원배열
print(m1)
m2=np.arange(9).reshape(3,3) #0~8, 9개의 숫자로 이루어진 배열
print(m2)
#m2=np.arange(9).reshape(3,4) #9개 숫잔데 12개를 만들어야 하니 오류발생
m2=np.arange(12).reshape(3,4)
print(m2)

m4=np.arange(11,11+12).reshape(3,4) # 11부터 12개의 숫자
print(m4)

l4 = [1,2,3,4,5] #2
l5 = [[1,2,3,4,5]] #2
print(l4[1])
print(l5[0][1])
#행이 한개인 2차원
m5=np.arange(1,4).reshape(1,3)
print(m5)
m6=np.arange(1,4).reshape(3,1)
print(m6)

#m4=np.arange(11,11+12).reshape(3,4) #3행4열
print(m4)
m7 = np.arange(11,23).reshape(4,3)   #4행3열
print(m7)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
2
2
[[1 2 3]]
[[1]
 [2]
 [3]]
[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]]
[[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]


In [109]:
# 3. array()함수를 사용하는 방법 : 리스트, 튜플을 이용
m9 = np.array([1,2,3])
print(m9)
m10=np.array([1,2,3])
print(m10)

#리스트를 포함한 리스트나 튜플을 포함한 튜플을 이용해서 2차원 배열을 만든다
m11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m11)
m12 = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(m12)
m13 = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(m13)
m14 = np.array(((1,2,3),(4,np.NaN,6),(7,8,np.NaN)))
print(m14)
#np.NaN : 결측지(Not A Number) : 알수 없는 값

[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8. nan]]


In [112]:
l1=[1,2,3]
l2=[3,2,1]
result = l1 + l2 # 연결
print(result)

x=np.array([1,2,3])
y=np.array([3,2,1])
result= x + y # 덧셈
print(result)

[1, 2, 3, 3, 2, 1]
[4 4 4]


In [118]:
#배열을 확장하기
print(x)
print(y)
z = np.concatenate((x,y))
print(z)
v = [99,99,99]
z = np.concatenate((x,y,v)) #배열에 리스트나 튜플 배열로 연결이 된다
print(z)

#리스트나 튜플도 배열로 확장 가능
z = np.concatenate(([1,2,3], (3,2,1), [99,99,99]))
print(z)
z = np.concatenate((l1,l2,v))
print(z)

[1 2 3]
[3 2 1]
[1 2 3 3 2 1]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]
[ 1  2  3  3  2  1 99 99 99]


In [124]:
#2차원 배열 확장하기
x2 = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4],
                 [3,2,1]])
grid1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
'''
z = np.concatenate((grid,x2), axis = 0) #열기준, x축기준
print(z)
concatenate를 사용하는 경우에는 차원이 같아야함
'''
z = np.concatenate((grid,grid1), axis = 0)
print(z)
z = np.concatenate((grid,grid1)) #axis = 0은 기본값임
print(z)
z = np.concatenate((grid,grid1), axis = 1) #axis = 1 : 행기준, y축기준
print(z)

[[9 8 7]
 [6 5 4]
 [3 2 1]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7 9 8 7]
 [6 5 4 6 5 4]
 [3 2 1 3 2 1]]


In [129]:
print(x2)
print(grid)
z = np.vstack((x2,grid)) #행은다른데 열이 같아서 가능
print(z)
'''
z = np.hstack((x2,grid)) #차원이달라서 안댐
print(z)
'''
grid2 = np.array([[1,2],[9,8],[7,6]])
print(grid2)

'''
[9 8 7] [1, 2]
[6 5 4] [9, 8]
[3 2 1] [7, 6]
'''
z = np.hstack((grid1,grid2)) #열은 다른데 행이같아서 가능
print(z)

[1 2 3]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2 3]
 [9 8 7]
 [6 5 4]
 [3 2 1]]
[[1 2]
 [9 8]
 [7 6]]
[[9 8 7 1 2]
 [6 5 4 9 8]
 [3 2 1 7 6]]


In [161]:
#유니버설 함수(UFuncs)
l1 = [1,2,3]
l2 = [3,2,1]
x = np.array(l1)
print(x)
y = np.array(l2)
result = x + y
print(result)
result = l1+l2
print(result)

[1 2 3]
[4 4 4]
[1, 2, 3, 3, 2, 1]


In [151]:
def add(i,j):
    l4 = []
    for idx in range(len(i)):
        l4.append(i[idx] + j[idx])
    return l4

In [152]:
result = add(l1,l2)
print(result)

[4, 4, 4]


In [163]:
result = x+y
print(result)
result = np.add(x,y)
print(result)
# + - * / % // **를 사용할때 자동으로 실행되는 : 유니버설 함수(UFuncs)
# 비교연산자에 대한 유니버셜함수도 있음
result = x-y
print(result)
result = np.subtract(x,y)
print(result)
result = x*y
print(result)
result = np.multiply(x,y)
print(result)
result = x/y
print(result)
result = np.divide(x,y)
print(result)

[4 4 4]
[4 4 4]
[-2  0  2]
[-2  0  2]
[3 4 3]
[3 4 3]
[0.33333333 1.         3.        ]
[0.33333333 1.         3.        ]


In [167]:
#브로드캐스팅
print(x)
print(y)
#배열을 연산하기 위해서는 창둰이 같아야함
z = x + 5 #1차원배열 + 정수 : [1 2 3] + [5 5 5] : 정수가 3열짜리 1차원 배열이 되어야 한다
print(z)
k = np.array([[1],[2],[3]])
print(k)

z = x + k
print(z)

print(grid)
z = grid + 5
print(z)

[1 2 3]
[3 2 1]
[6 7 8]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[14 13 12]
 [11 10  9]
 [ 8  7  6]]


In [172]:
#넘파이함수
#제로행렬
m = np.zeros(3)
print(m)
m = np.zeros((3,3))
print(m)
#원(1)행렬
m = np.ones(3)
print(m)
m = np.ones((3,3))
print(m)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [182]:
#집계함수
l = [1,2,3,4,5,6]
print(max(l)) #내장함수
print(min(l))
print(sum(l))

m = np.random.randint(3, size=6)
print(m)
print(sum(m))
print(np.sum(m))
print(m.sum())
print(np.sum(l))

print(m.max())
print(np.max(m))
print(m.min())
print(np.min(m))

6
1
21
[2 1 0 1 0 0]
4
4
4
21
2
2
0
0


In [188]:
m = np.random.random((4,3)) # 0~1사이의 값
print(m)
print(sum(m)) #열의 합계
print(np.sum(m)) #집계 합
print(m.sum())
print(np.max(m)) #집계 최대값
print(m.max())
print(np.min(m)) #집계 최소값
print(m.min())

[[0.19258767 0.85842702 0.78358282]
 [0.88531216 0.98399099 0.68224312]
 [0.79544402 0.27412265 0.27151212]
 [0.88941747 0.10836941 0.6347771 ]]
[2.76276131 2.22491007 2.37211516]
7.3597865359542345
7.3597865359542345
0.9839909882852043
0.9839909882852043
0.10836940748567592
0.10836940748567592
